
[build]
command = "npm run build"
publish = "dist/public"
functions = "netlify/functions"

[[redirects]]
from = "/.netlify/functions/*"
to = "/.netlify/functions/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = true

[[headers]]
for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"
